### PR TITLE
Add Title.getPrefixedText method to get readable title text

### PR DESCRIPTION
**Pull request by santhoshtr**
This is copy of getPrefixedText method that exist in mediawiki core
mediawiki.Title.js#getPrefixedText

Testcase included.

### CODE REVIEW

**Comment by Pchelolo** [comment]
The listing rules are failing, otherwise lgtm

**Comment by santhoshtr** [comment]
> The listing rules are failing, otherwise lgtm

I fixed the linting now.

**Comment by santhoshtr** [comment]
Thanks @Pchelolo. Will you do an update to npm package now? We are using this for [cxserver](https://github.com/wikimedia/mediawiki-services-cxserver/blob/master/package.json#L30)

**Comment by Pchelolo** [comment]
@santhoshtr done. published as 0.6.4.

**Pull request merged**
