### PR TITLE
Add Title#equals(), Namespace#equals(), and Namespace#getId()

### PR DESCRIPTION
**Pull request by cscott**
Make it easy to compare titles and namespaces for equality, and expose the numeric namespace identifier.

### CODE REVIEW

**Comment by Pchelolo** [comment]
Tabs alert from travis and me

**Comment by cscott** [comment]
Should be fixed now.  I added some tests for good measure.

**Comment by Pchelolo** [comment]
LGTM.

**Comment by Pchelolo** [comment]
@cscott do you have more coming or should we release?

**Comment by cscott** [comment]
Nope, this is it.  Thanks!

**Pull request merged**
