### PR TITLE
Don't upper-case if it ends up as a multiletter string

### PR DESCRIPTION
**Pull request by Pchelolo**
cc @wikimedia/services 
Bug: https://phabricator.wikimedia.org/T141723

### CODE REVIEW

**Comment by gwicke** [comment]
@Pchelolo, my understanding re the PHP limitation was that they had not updated their unicode data in a long time, but if they did, they might start to handle multi-char characters (and there might not be a guarantee that they don't yet right now). 

An alternative test we considered in the past was to check whether `s.toUppercase().toLowerCase() === s`. This would catch the multi-char case, but could potentially also identify other non-bijective edge cases, which might or might not be problematic in PHP as well. Which advantages / disadvantages do you see between these options?

**Comment by gwicke** [comment]
Actually, after reading the linked task it seems that right now PHP is indeed limited to single-codepoint replacements, so testing the length ought to be accurate. There could still be cases where PHP has old unicode data & doesn't transform non-bijective single-char cases that JS would, but it seems that the length option would be the more conservative first step. We could still move to the round-trip test later if additional cases are found that are not caught by the length check.

So, :+1: from me.

**Comment by Pchelolo** [comment]
@gwicke both of these tests are basically an approximation and they both could potentially backfire, but I think that the length check is more conservative. Although, may be we should explicitly check for ß ?

**Comment by Pchelolo** [comment]
Okey, this PR is wrong... It wouldn't work for all of the characters out of the basic multilingual unicode plain. So, for example `'🎉'.toUpperCase().length === 2`. For emoji that might not be a problem because they don't have upper-cased versions, but there might be symbols out of the basic plane that would hit this issue.

**Comment by Pchelolo** [comment]
Actually, this whole method is very wrong, because of the emoji: `'🎉'.substr(0,1).toUpperCase()` returns nothing since we've uppercased only the first half of the surrogate symbol.

**Comment by berndsi** [comment]
Doh. Should have refreshed the page before I sent my comment.

**Comment by Pchelolo** [comment]
Updated. This should do the trick better then the previous check. Unfortunately has to introduce a dependency

**Comment by Pchelolo** [comment]
Actually, we don't need to mangle with astral plane characters here. For astral plane characters the `charAt(0)` will give a surrogate unicode symbol, uppercasing will not change it and we will reconstruct the code point back by adding a `.substr(1)`. So emojis are fine.

**Comment by Pchelolo** [comment]
Published as `mediawiki-title@0.5.6`

**Pull request merged**
