### PR TITLE
newFromText should accept a default namespace

### PR DESCRIPTION
**Pull request by arlolra**
Needed to do something like,

```
$title = Title::newFromText( $matches[1], NS_FILE );
```

https://github.com/wikimedia/mediawiki/blob/master/includes/parser/Parser.php#L4926

/cc @subbuss

### CODE REVIEW

**Comment by Pchelolo** [comment]
LGTM, waiting for travis and merging

**Comment by Pchelolo** [comment]
@arlolra Could you bump a package version so that I could release a new version?

**Comment by arlolra** [comment]
Sure, I should update the readme as well.

Although, I have another patch coming.  Maybe I'll wait on that?

**Comment by Pchelolo** [comment]
@arlolra Ok, let's bump the version in the next patch then, merging.

**Pull request merged**
